oktadev/okta-aws-cli-assume-role

.gitignore, src/main/java/com/okta/tools/awscli.java
Removed check on role_arn value being blank or not since this interferes with the default profile update (which might not need a role_arn value in the ~/.aws/config file). 
This parameter will not be updated if blank in the WriteNewRoleToAssume function anyway.
Also fixed code formatting using IntelliJ built-in Reformat Code menu.
@ibabiy-okta, do you think you could review this tiny update? Thanks :)
=> Config file update fix

src/main/java/com/okta/tools/awscli.java
So that the tool could be invoked from any directory.
=> Allows to find properties file by absolute path

src/main/java/com/okta/tools/awscli.java
The current implementation requires a config.properties in the path to be able to work
Solution
--------
If the config.properties is not found, then the configuration loader fallback on the classpath configuration, allowing to still do local configuration and package a default one
=> Load from classpath if config.properties is not found

src/main/java/com/okta/tools/OktaAwsCliAssumeRole.java
Currently the HttpClient building does not use system settings, therefore proxies are not supported.
Solution
--------
Updated to use createSystem() so that system settings are used.
=> 2017_12_20 - Adding Proxy/System Setting Support

src/main/java/com/okta/tools/OktaAwsCliAssumeRole.java
If role is not found the error message will generate
```
Please choose the role you would like to assume:
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 
```
The i will have been increased until array size, so the get(i) will always fail
Solution
--------
Just display the searched role from parameter
=> Fix error message if role is not found

src/main/java/com/okta/tools/OktaAwsCliAssumeRole.java
The default jar included in the repo resulted in an unusable UI (role names were listed incorrectly and could not be successfully selected).
Solution
--------
Built a new jar file for inclusion in the /out dir. Also improved error-checking for reading a default role from the config.properties file (now checks for empty string in addition to null).
Before:
After:
=> fixes jar, adds ec to default role

out/awscli.bat, src/main/java/com/okta/tools/OktaAwsCliAssumeRole.java
Current menu selection was broken.
Bat file was not accepting additional arguments (ie: .\awscli.bat s3 ls) would not accept the **s3 ls** args.
Solution
--------
Fixed menu selection, fixed bat file.
=> Menu Selection/Bat File Fixes

out/withokta, out/withokta.bat, src/main/java/com/okta/tools/OktaAwsCliAssumeRole.java, src/main/java/com/okta/tools/OktaAwsConfig.java, src/main/java/com/okta/tools/WithOkta.java, src/main/java/com/okta/tools/awscli.java
Cannot make profiles for multiple environments using Okta.
Solution
--------
Added withokta command that takes the environment variable in the shell and creates a profile for it. This command operates like sudo in that it runs the entire command handed to it. This could be used for things like Terraform or Serverless. You could do a command like env OKTA_PROFILE=prod ./withokta aws --profile prod s3 ls.
=> BC-ProfileNames

src/main/java/com/okta/tools/aws/settings/Configuration.java, src/main/java/com/okta/tools/aws/settings/Credentials.java, src/test/java/com/okta/tools/aws/settings/ConfigurationTest.java, src/test/java/com/okta/tools/aws/settings/CredentialsTest.java
Attempting to use **withokta** with a named profile and PowerShell downstream leads to an error like this:
```powershell
Credential profile [Corp] is not valid.  Please ensure the profile contains a valid combination of properties.
```
Solution
--------
Use a distinct name for the source_profile saved to ~/.aws/credentials. This works for PowerShell, AWS CLI, Python programs using boto3, and AWS SDK for Java. It likely works for other AWS SDKs as well.
=> Support for AWS Tools for Windows PowerShell

src/main/java/com/okta/tools/OktaAwsCliAssumeRole.java, src/main/java/com/okta/tools/WithOkta.java, src/main/java/com/okta/tools/aws/settings/MultipleProfile.java
It is required that MFA must be used every time a new profile is made or refreshed.
Solution
--------
The Session ID cookie is saved and reused so that the session will refresh as long as the session is still valid.
=> Reusing Okta Session ID

Readme.MD, bin/awscli, bin/awscli.bat, bin/withokta, bin/withokta.bat, src/main/java/com/okta/tools/OktaAwsConfig.java
Issue #88 highlights that forcing config.properties to be in the working directory makes this difficult to roll out or install.
Solution
--------
- Allow use with config.properties in current working directory
- Allow use with just environment variables and no config.properties
- Add scripts that work anywhere on **PATH** as long as JAR is in ~/.okta/
=> :seedling: Install-friendly config and scripts

src/main/java/com/okta/tools/aws/settings/Configuration.java
The profile management introduced in #81 (merged to master) overwrites the region in ~/.aws/config.
Solution
--------
If profile in ~/.aws/config has region set, leave it as is.
=> :bug: Fix #46 by reusing existing region

src/main/java/com/okta/tools/OktaAwsCliAssumeRole.java
When AWS directories or config files are missing, this tool can fail ungracefully.
Solution
--------
Self-heal AWS directories and config files when safe, show errors when impossible or unsafe.
=> :seedling: Self-heal missing AWS configuration

src/main/java/com/okta/tools/OktaAwsCliAssumeRole.java
Symantec VIP and RSA tokens aren't accepted as factors right now.
Solution
--------
Add support for "token" type factors. Fix https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/74.
=> :bug: RSA and Symantec VIP tokens not accepted

src/main/java/com/okta/tools/OktaAwsCliAssumeRole.java
- Allow profile name to be null again
- Use auto-generated session if named profile is blank or null
Fix #94
Fix #95
Solution
--------
=> :bug: NPE on second run with no profile name

Readme.MD
macOS-specific commands referenced in README without clarification.
Solution
--------
Remove references. Clarifying or providing multi-platform answers to this is tangly and better addressed in AWS' own docs.
=> :bug: :memo: Fix #30 by removing macOS reference

src/main/java/com/okta/tools/helpers/RoleHelper.java
Debugging output is printed on the console during login. This clutters the output and confuses users.
Solution
--------
Don't show the debugging output.
=> :art: Remove debugging output during auth flow

src/main/java/com/okta/tools/BrowserAuthentication.java, src/main/java/com/okta/tools/OktaAwsCliAssumeRole.java, src/main/java/com/okta/tools/OktaAwsCliEnvironment.java, src/main/java/com/okta/tools/OktaAwsConfig.java, src/main/java/com/okta/tools/WithOkta.java, src/main/java/com/okta/tools/authentication/BrowserAuthentication.java, src/main/java/com/okta/tools/awscli.java, src/main/java/com/okta/tools/helpers/CookieHelper.java, src/main/java/com/okta/tools/helpers/SessionHelper.java, src/main/java/com/okta/tools/saml/OktaSaml.java, src/main/java/com/okta/tools/util/NodeListIterable.java
App-based MFA and Okta's Duo Push integration don't work from a CLI-based interaction.
Solution
--------
Perform browser-based authentication using an embedded JavaFX WebView.
Capture SAMLResponse and sid for downstream use.
Testing
--------
Add `OKTA_BROWSER_AUTH=true` to **~/.okta/config.properties**
Run `env OKTA_PROFILE=dev awscli logout`
Run `env OKTA_PROFILE=dev awscli sts get-caller-identity`, expect browser auth experience to appear
Authenticate via JavaFX WebView
Expect prompt for role in CLI
Pick a role (any role, it doesn't matter)
Expect it to output information about the assumed role
Run `env OKTA_PROFILE=dev awscli sts get-caller-identity`, expect no auth
Expect it to output information about the assumed role
Run `env OKTA_PROFILE=dev2 …
=> :seedling: Browser-based authentication

Readme.MD
Some properties in config.properties aren't documented.
Solution
--------
Add documentation for OKTA_PROFILE and OKTA_BROWSER_AUTH.
=> :memo: Fill in config.properties documentation

src/main/java/com/okta/tools/AWSCredentialsUtil.java, src/main/java/com/okta/tools/OktaAwsCliAssumeRole.java
Add authentication support when using AWS java sdk.
Solution
--------
When working with AWS java sdk it’s now possible to use
```
AWSCredentials credentials = AWSCredentialsUtil.getAWSCredential();
AWSStaticCredentialsProvider credentialsProvider = new AWSStaticCredentialsProvider(credentials);
```
to create the necessary credentials in order to make api calls.
=> :seedling: Adds authentication support when using AWS java sdk

src/main/java/com/okta/tools/authentication/BrowserAuthentication.java
The in browser auth with MFA, not tested without, doesn't catch the samlresponse needed to close  it and proceed auth.
This because the page who has the form with the needed input with the samlresponse doesn't have the SUCCEED state in the redirects.
Solution
--------
Verify all page during redirects.
=> Check all pages to verify the samlresponse in browser auth

pom.xml
On OSX, users sometimes get an empty role list while Linux users do not
esperience problems. This holds even true when the same Docker image is
used.
Solution
--------
We tracked this down to the document in `AwsSamlSigninParser` (the HTML document
that represents the HTML page AWS presents for selecting roles after login to
Okta) being broken judging by string representation of the `Document` object.
However, we noticed when converting the HTML response to a string before
passing it to `Jsoup.parse`, the error disappeared:
```java
// in AwsSamlRoleUtils.getSigninPageDocument
Scanner s = new Scanner(samlSigninResponse.getEntity().getContent()).useDelimiter("\\A");
String result = s.hasNext() ? s.next() : "";
System.out.println(result);
return …
```
=> Fix #138: Update Jsoup to 1.11.3

Readme.MD, src/main/java/com/okta/tools/OktaAwsCliEnvironment.java, src/main/java/com/okta/tools/OktaAwsConfig.java, src/main/java/com/okta/tools/aws/settings/Configuration.java, src/main/java/com/okta/tools/awscli.java, src/main/java/com/okta/tools/helpers/ConfigHelper.java, src/test/java/com/okta/tools/aws/settings/ConfigurationTest.java
1. Currently AWSCLI profiles always default to us-east-1, one of many AWS regions.  It is not possible to change this with the current published jar.
2. For organizations with many AWS accounts, there is often a need to  access multiple profiles on a daily basis.  Currently this requires modifying OKTA_PROFILE in the environment or config.properties files to create a friendly profile name.
Solution
--------
1. Allow default region to be specified via OKTA_AWS_REGION
2. Allow OKTA_PROFILE to be specified on the awscli commandline via the --profile option.
=> Add custom region and profiles

pom.xml
The jarfile is unneccessarily huge because the full AWS Java SDK is included.
Solution
--------
AWS conciously splitted the SDK in a myriad of Jarfiles, so one must only include the required ones.
=> Pom: Do not include full AWS SDK

bin/Install-OktaAwsCli.ps1
PowerShell profile crashes with no Internet Options proxy set.
Solution
--------
Only do proxy selection if there is a proxy server.
=> :bug: Fix #153 PowerShell crash with no proxy

Readme.MD, src/main/java/com/okta/tools/aws/settings/Configuration.java
The fix for #161 still unconditionally uses `_source` when writing the AWS configuration file.
Solution
--------
Use the environment setting `OKTA_CREDENTIALS_SUFFIX` (or its default value if not set) instead of `_source`.
=> Use credentials suffix in AWS configuration

bin/install.sh
(only tested on Mac OSX 10.13.8, High Sierra)
```
Running the bash functions as-is gives this stack trace:
`` ~  aws okta sts get-caller-identity
Exception in thread "main" java.io.IOException: Cannot run program "aws --profile okta": error=2, No such file or directory
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
at com.okta.tools.WithOkta.main(WithOkta.java:25)
Caused by: java.io.IOException: error=2, No such file or directory
at java.lang.UNIXProcess.forkAndExec(Native Method)
at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
at java.lang.ProcessImpl.start(ProcessImpl.java:134)
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
... 1 more
```
Solution
--------
Change to be much simpler, and pass the arguments to withokta …
=> fix bash functions to work as documentation states 

src/main/java/com/okta/tools/OktaAwsConfig.java, src/main/java/com/okta/tools/authentication/OktaAuthentication.java, src/main/java/com/okta/tools/authentication/TransactionState.java
Was getting json responses from the authn call that were of 'status' : 'MFA_ENROLL' , and had no 'sessionToken', but did have a `stateToken`. The app crashed with a JSON parse error with very little useful information. 
```
→ okta sts get-caller-identity
Username: XXXXXXX
Password:
Exception in thread "main" org.json.JSONException: JSONObject["sessionToken"] not found.
at org.json.JSONObject.get(JSONObject.java:520)
at org.json.JSONObject.getString(JSONObject.java:806)
at com.okta.tools.authentication.OktaAuthentication.getOktaSessionToken(OktaAuthentication.java:40)
at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:46)
at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:106)
at …
```
=> Rework auth request code to provide useful error messages

Readme.MD, docs/OKTA_PASSWORD_CMD.md, src/main/java/com/okta/tools/OktaAwsConfig.java
OKTA_PASSWORD is not stored securely. Having this feature in is a
security risk for users.
Solution
--------
- Remove documentation for OKTA_PASSWORD
- Remove support for OKTA_PASSWORD
Resolves #171
Will revisit with support for a password command as recommended in #12
=> :lock: Remove plaintext saved password support

src/main/java/com/okta/tools/authentication/BrowserAuthentication.java
> Manually closing the browser auth window with the embedded browser doesn't quit the program. It stays running in a stuck/broken state.
Solution
--------
- Clicking close exits the application with code 1
Resolves #163
=> :bug: Closing browser auth doesn't quit

pom.xml, src/main/java/com/okta/tools/aws/settings/AwsINIConfiguration.java, src/main/java/com/okta/tools/aws/settings/Configuration.java, src/main/java/com/okta/tools/aws/settings/Credentials.java, src/main/java/com/okta/tools/aws/settings/MultipleProfile.java, src/main/java/com/okta/tools/aws/settings/Settings.java, src/main/java/com/okta/tools/helpers/ConfigHelper.java, src/main/java/com/okta/tools/helpers/CookieHelper.java, src/main/java/com/okta/tools/helpers/CredentialsHelper.java, src/main/java/com/okta/tools/helpers/FileHelper.java, src/main/java/com/okta/tools/helpers/SessionHelper.java, src/test/java/com/okta/tools/aws/settings/ConfigurationTest.java, src/test/java/com/okta/tools/aws/settings/CredentialsTest.java, src/test/java/com/okta/tools/aws/settings/SettingsTest.java
Issue #141 states:
> Existing `~/.aws/config` with nested properties are overwritten improperly by this tool.
> For example, `s3` configuration uses [indentation for its properties](https://docs.aws.amazon.com/cli/latest/topic/s3-config.html) e.g.
> ```
> [profile development]
> aws_access_key_id=foo
> aws_secret_access_key=bar
> s3 =
>   max_concurrent_requests = 20
>   max_queue_size = 10000
> ```
> When `awscli` is run, the `config` is written out like so:
> ```
> [profile development]
> aws_access_key_id=foo
> aws_secret_access_key=bar
> s3 =
> max_concurrent_requests = 20
> max_queue_size = 10000
> ```
> which is not correctly read by `aws s3` commands!
> 
> Specifically, the following test …
=> :bug: Correctly handle nested configs

src/main/java/com/okta/tools/saml/OktaSaml.java
When app sign on policies are unsupported the tool responds like this:
```plain
You do not have access to AWS through Okta.
Please contact your administrator.
```
That is inaccurate and confusing and leads to issue reports that would be better handled as feature requests with use cases outlined.
Solution
--------
- Differentiate sign-on failure due to app-level MFA
- Differentiate sign-on failure due to app-level re-auth challenge
- Use failure message from Okta when available otherwise
=> :art: Clearer app sign on rule failure messages

bin/install.sh
Issue #187 states:
> **Is your feature request related to a problem? Please describe.**
> Currently, the install.sh is hard-coded to install the v1.0.2 release. We recently released v1.0.3. The install.sh script should default to the latest release version.
> 
> **Describe the solution you'd like**
> It would probably make sense to have a simple file like latest.txt that stores the latest release version that install.sh could refer to. latest.txt would have to be manually updated whenever we do a new release.
> 
> **Describe alternatives you've considered**
> I can't think of a more automated way to do this, but there probably is one.
> 
> It seems like the install.sh script is becoming the preferred way to install the tool, …
=> :bug: Release version is hard-coded in bin/install.sh

Readme.MD, src/main/java/com/okta/tools/OktaAwsCliAssumeRole.java, src/main/java/com/okta/tools/OktaAwsCliEnvironment.java, src/main/java/com/okta/tools/OktaAwsConfig.java, src/main/java/com/okta/tools/WithOkta.java, src/main/java/com/okta/tools/authentication/OktaAuthentication.java, src/main/java/com/okta/tools/awscli.java, src/main/java/com/okta/tools/helpers/ProfileHelper.java, src/test/java/com/okta/tools/aws/settings/ConfigurationTest.java, src/test/java/com/okta/tools/aws/settings/CredentialsTest.java
#177 states:
> It'd be handy if there's an option to export "AWS_ACCESS_KEY_ID, AWS_SECRET_KEY, AWS_SESSION_TOKEN" as EnvVars in lieu of writing to the AWS profiles file.
>
>Use case would be for any tools that can load auth from those EnvVars.
Solution
--------
- Introduce OKTA_ENV_MODE
- Add documentation for OKTA_ENV_MODE
- Run sub-process with env vars instead of saved profiles
- :bug: Defer password command
Resolves #177
=> :seedling: Add support for EnvVars integration

bin/Install-OktaAwsCli.ps1
The PowerShell install script also faces the same problem described in #187.
Solution
--------
The url of the latest released jar is obtained from the [get-latest-release github api](https://developer.github.com/v3/repos/releases/#get-the-latest-release) and the url is used to download the file.
=> :bug: Download latest released jar file to install

src/main/java/com/okta/tools/helpers/ConfigHelper.java, src/main/java/com/okta/tools/helpers/CredentialsHelper.java, src/main/java/com/okta/tools/helpers/FileHelper.java, src/main/java/com/okta/tools/helpers/SessionHelper.java
Issue #197 states:
> `updateConfigFile` in `ConfigHelper` https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/87f90ac171ae3888d6681bc2b5c0781433353a34/src/main/java/com/okta/tools/helpers/ConfigHelper.java#L21 is unable to read existing AWS configs.
> The root bug apears to be in `usingPath` in `FileHelper` https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/87f90ac171ae3888d6681bc2b5c0781433353a34/src/main/java/com/okta/tools/helpers/FileHelper.java#L113 that opens both a `Reader` and `Writer` to the same file. However, creating a new `FileWriter` https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/87f90ac171ae3888d6681bc2b5c0781433353a34/src/main/java/com/okta/tools/helpers/FileHelper.java#L90 on …
=> :bug: Overwriting, not updating config files

src/main/java/com/okta/tools/CredentialProcess.java, src/main/java/com/okta/tools/LogoutHandler.java, src/main/java/com/okta/tools/OktaAwsCliAssumeRole.java, src/main/java/com/okta/tools/authentication/OktaAuthentication.java, src/main/java/com/okta/tools/authentication/OktaMFA.java, src/main/java/com/okta/tools/helpers/MenuHelper.java, src/main/java/com/okta/tools/helpers/RoleHelper.java
Issue #59 states:
> This was talked about in the recent [AWS CLI talk at re:Invent ](http://awsfeed.com/post/168047446129/aws-reinvent-2017-aws-cli-2017-and-beyond)
> 
> By supporting returning a specific JSON object, as described here: http://docs.aws.amazon.com/cli/latest/topic/config-vars.html#sourcing-credentials-from-external-processes [okta-aws-cli-assume-role](https://github.com/oktadeveloper/okta-aws-cli-assume-role) can integrate better with the [aws-cli](https://aws.amazon.com/cli/) command.
> 
> See example here: https://github.com/awslabs/awsprocesscreds
> 
> /cc: @AlainODea @mraible @rdegges @joelfranusic-okta
Solution
--------
- Add CredentialProcess entry-point
- Move logging/console interaction to STDERR (allow 2>/dev/null)
- Depends on …
=> :seedling: Support for credential_process

src/main/java/com/okta/tools/authentication/OktaMFA.java
Issue #215 states:
> 
> When token verification fails the `java.lang.NullPointerException` error shows up after entering token again.
> 
> _Example 1:_
> 
> ```
> Username: ***@***.com
> 
> GOOGLE Token Factor Authentication
> Enter 'change factor' to use a different factor
> Token:
> 111111
> Invalid Passcode/Answer
> Please try again
> 
> GOOGLE Token Factor Authentication
> Enter 'change factor' to use a different factor
> Token:
> 932072
> Exception in thread "main" java.lang.NullPointerException
> 	at com.okta.tools.authentication.OktaMFA.handleTimeoutsAndChanges(OktaMFA.java:77)
> 	at com.okta.tools.authentication.OktaMFA.promptForFactor(OktaMFA.java:54)
> 	at com.okta.tools.authentication.OktaAuthentication.getOktaSessionTok …
```
=> :bug: NPE on second TOTP attempt

bin/install.sh
Issue #175 states:
> When following the installation instructions the install shell script fails here due to insufficient priveleges:
> https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/master/bin/install.sh#L80-L86
> 
> Should this command be run with `sudo`?
Solution
--------
- Provide overridable PREFIX (default /usr/local)
Resolves #175
=> :bug: Requires sudo to install on CentOS

pom.xml, src/main/java/com/okta/tools/OktaAwsCliAssumeRole.java, src/main/java/com/okta/tools/helpers/CredentialsHelper.java, src/main/java/com/okta/tools/helpers/ProfileHelper.java, src/test/java/com/okta/tools/helpers/ProfileHelperTest.java
Issue #208 states:
> please see discussion here: [aws/aws-sdk-java-v2#389 (comment)](https://github.com/aws/aws-sdk-java-v2/issues/389#issuecomment-421195380)
Solution
--------
- Use roleName_account as generated role name (fallback to "temp")
Resolves #208
=> :bug: Profile names break AWS Java SDK 2

bin/Install-OktaAwsCli.ps1, bin/install.sh, bin/okta-listroles, src/main/java/com/okta/tools/ListRoles.java, src/main/java/com/okta/tools/helpers/RoleHelper.java
Issue #223 states:
> 
> Given a user who has multiple roles in a given AWS account, how can I:
> 
>     1. Retrieve the list of possible roles on behalf of the user so that I can do something programmatic with them?
> 
>     2. Get credentials for a different role on that account while the credentials for the first role are active?
> 
> 
> I'm presuming that if I knew which role they wanted to assume, I could set the OKTA_PROFILE to be some combination of the account name/id and the role (which is what the code does by default). This would solve #2. But, without knowing which roles are assumable by the user, I cannot set the profile name to something that would trigger the second credentials because just running `withokta` with …
=> :seedling: Machine-consumable role list

docs/OKTA_PASSWORD_CMD.md
Lack of `OKTA_PASSWORD_CMD` examples.
Solution
--------
Added usage example for GNU/Linux GNOME Keyring for `OKTA_PASSWORD_CMD`
=> New OKTA_PASSWORD_CMD usage example

.gitignore, Readme.MD, src/main/java/com/okta/tools/OktaAwsCliEnvironment.java, src/main/java/com/okta/tools/OktaAwsConfig.java, src/main/java/com/okta/tools/aws/settings/Credentials.java, src/main/java/com/okta/tools/aws/settings/MultipleProfile.java, src/main/java/com/okta/tools/helpers/CredentialsHelper.java, src/main/java/com/okta/tools/helpers/ProfileHelper.java, src/main/java/com/okta/tools/helpers/RoleHelper.java, src/main/java/com/okta/tools/helpers/SessionHelper.java, src/test/java/com/okta/tools/aws/settings/CredentialsTest.java, src/test/java/com/okta/tools/helpers/ProfileHelperTest.java
Should resolve: https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/43
Solution
--------
Revert commit b86dc34 to give us back `OKTA_AWS_REGION`, then refactor how this is passed between environments
=> Add ability to pass in OKTA_AWS_REGION and use it for other regions for STS

src/main/java/com/okta/tools/helpers/SessionHelper.java
OKTA_ENV_MODE does not update the current session, but will
(unintentionally) make use of the one that is there. This can lead to
dangerous confusing situations where the program run is run with the
credentials of the current session and not the fresh credentials
obtained for OKTA_ENV_MODE.
Solution
--------
- Suppress current session if OKTA_ENV_MODE is true
=> :bug: Current session used in OKTA_ENV_MODE

bin/install.sh
Issue #234 states:
> All I know for sure is that after following the install instructions, I cannot execute `okta-aws`. I've been debugging and I already notice one huge bug, which is that the installer added
> 
> ```
> export PATH="$HOME/bin:$PATH"
> ```
> 
> to my `config.fish`. That syntax is valid in `bash`, but in fish it should probably be
> 
> ```
> set -x PATH $HOME/bin $PATH
> ```
> 
> Furthermore, it didn't even create a `/bin` folder in my `$HOME` directory.
> 
> 
>     1. Install the fish shell
> 
>     2. Execute
> 
> 
> ```
> curl 'https://raw.githubusercontent.com/oktadeveloper/okta-aws-cli-assume-role/master/bin/install.sh' | bash
> ```
> 
>     1. Check your …
=> :bug: Fish install broken

Readme.MD
As @ohuk2 reported in #225, the requirement for /usr/local/bin (or $PREFIX/bin) is not documented.
Solution
--------
- Make clear that /usr/local/bin (or $PREFIX/bin) needs to be in PATH
Resolves #225's root cause.
=> :memo: Clarify PATH requirements

Readme.MD, bin/install.sh, docs/man/okta-credential_process.1.md, docs/man/okta-listroles.1.md, src/main/java/com/okta/tools/CredentialProcess.java, src/main/java/com/okta/tools/OktaAwsCliEnvironment.java
Issue #232 states:
> CredentialProcess no longer works. It's not clear why.
> 
> 
>     1. Set up default profile to use credential_process as follows:
>        ```ini
>        [default]
>        credential_process = java -cp /Users/username/.okta/okta-aws-cli.jar com.okta.tools.CredentialProcess
>        ```
> 
>     2. Run `aws sts get-caller-identity`
> 
>     3. Provide Okta credentials when prompted
> 
>     4. See error:
>        ```
>        can only concatenate str (not "NoneType") to str
>        ```
> 
> 
> Case 2: running CredentialProcess directly:
> 
>     1. Run `java -cp /Users/username/.okta/okta-aws-cli.jar com.okta.tools.CredentialProcess`
> 
>     2. See …
=> :bug: CredentialProcess is unusable

Readme.MD
When I was installing on mac it tried to install in /usr/local/bin/bin
Solution
--------
Change Prefix env when installing
```
ignacio.tolstoy in ~/code  $ export PREFIX=/usr/local/bin
ignacio.tolstoy in ~/code  $ curl 'https://raw.githubusercontent.com/oktadeveloper/okta-aws-cli-assume-role/master/bin/install.sh' | bash
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  3284  100  3284    0     0   8532      0 --:--:-- --:--:-- --:--:--  8552
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   612    0   612    0     0   1406      0 --:--:-- --:--:-- --:--:--  1410
100 51.9M  100 51.9M    0     0 …
```
=> Prefix should be /usr/local

bin/Install-OktaAwsCli.ps1
A comment on issue #85 states:
> @AlainODea FYI, the documentation hasn't been updated yet.
> 
> I had this issue today (this is why I am here!); I had installed the AWS CLI tools via the MSI installer, which creates an `aws.cmd` batch file which itself calls into the Python 3.6 interpreter the MSI installer installs in `C:\Program Files\Amazon\AWSCLI\runtime\`.
> 
> I then ran the command to install okta-aws-cli-assume-role using `Install-OktaAwsCli.ps1`, and received the IOException upon verifying my setup.
> 
> The fix, as was suggested here, was to update the powershell $profile to change `aws` to `aws.cmd`.
> 
> Can this issue be fixed in `Install-OktaAwsCli.ps1` by checking the output of `Get-Command aws.cmd`, and - if a result is returned - …
=> :bug: AWS command filename isn't always "aws"

src/main/java/com/okta/tools/authentication/BrowserAuthentication.java, src/main/java/com/okta/tools/authentication/CookieManager.java, src/main/java/com/okta/tools/helpers/CookieHelper.java, src/main/java/com/okta/tools/saml/OktaSaml.java
Issue #25 states:
> We use application level sign on policies to enforce MFA for specific applications, however the cli tool doesn't support this. I saw an closed issue from August due to lack of API support. Has this been added to the API? Is there some other solution to this problem?
Solution
--------
- Use stored cookies for browser authentication
- Use browser for subsequent authentications when
OKTA_BROWSER_AUTH=true
- Use RFC6265 cookie parsing provided by Apache HTTP Components
- Provide a CookieHandler that delegates to JFX and saves cookies as
they are updated by HTTP responses
Resolves #25
=> :seedling: Support app-level MFA

bin/Install-OktaAwsCli.ps1
Issue #244 states:
> Exception in thread "main" java.net.UnknownHostException: socks=localhost
> 
> 
>     1. windows
> 
>     2. manually configure a localhost socks proxy in internet options, notice that browser uses proxy (edge/chrome, not ff) (ssh "dynamic" socks is common)
> 
>     3. disable the proxy, notice that browser does not use proxy
> 
>     4. notice that okta-aws-cli-assume-role tries to use the proxy
> 
> 
> respects proxy setting like browser.
> 
> I think the registry HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ProxyEnable should be checked. As well the value of …
=> :bug: SOCKS proxy won't work on Windows

src/main/java/com/okta/tools/authentication/OktaAuthentication.java, src/main/java/com/okta/tools/authentication/OktaMFA.java
Issue #249 states:
> If a password has expired, the CLI crashes with a vague null pointer exception after the username, password, and MFA token have already been accepted.
> 
> 
>     1. Ensure your password has expired
> 
>     2. Run `awscli sts get-caller-identity`
> 
>     3. Input your Username, Password, and Token
> 
>     4. See error
> 
> 
> Some form of description along with the stack trace that indicates the password has expired, perhaps similar to how #101 includes the `java.lang.RuntimeException: You do not have access to AWS through Okta.` bit.
> 
> 
> ```
> [matt@matt-dev ~]$ awscli sts get-caller-identity
> …
```
=> :bug: Crash encountered if password has expired

src/main/java/com/okta/tools/helpers/SessionHelper.java
Issue #239 states:
> The ~/.okta/.current_session file is used even if the org is switched. This can lead to dangerous surprises.
> 
> 
>     1. Run `okta-aws test sts-get-caller-identity`
> 
>     2. Change OKTA_ORG in ~/.okta/config.properties
> 
>     3. Run `okta-aws test sts-get-caller-identity`
> 
>     4. See STS output for previous OKTA_ORG and no auth prompts
> 
> 
> Session should not be org-aware. If I have a non-expired session on the new OKTA_ORG setting, it should be reused. If not, I should be prompted for authentication.
> 
> **Screenshots**
> N/A
> 
> v1.0.5
Solution
--------
- Add OKTA_ORG to .current-session on …
=> :bug: Session not invalidated on org switch

Readme.MD, bin/install.sh
Install script is (1) difficult to read, (2) does not print critical information about what it is doing, (3) silently modifies `~/.bash_profile`, and (4) writes files to multiple locations in the filesystem, a change that is difficult to revert unless there is a corresponding uninstallation mechanism.
Solution
--------
1. Update the install script to make it easier to read using here documents
2. Print information about what it is doing
3. Print advice about how to modify `~/.bash_profile` and how to proceed post-installation
4. Write all files to `~/.okta` so that uninstalling only involves removing that directory
=> Improve install script

pom.xml
It is not practical to determine what version of this is in use when troubleshooting.
Solution
--------
- Include implementation entries in JAR manifest
Existing META-INF/MANIFEST.MF looks like this:
```
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven
Built-By: alain.odea
Build-Jdk: 11.0.1
```
Add these entries to the above (auto-generated):
```
Implementation-Title: okta-aws-cli
Implementation-Version: 1.0.9-SNAPSHOT
Implementation-Vendor-Id: com.okta.developer
Main-Class: com.okta.tools.awscli
```
=> :hammer: JAR manifest including version

src/main/java/com/okta/tools/authentication/BrowserAuthentication.java, src/main/java/com/okta/tools/io/LoginPageInterceptingProtocolHandler.java, src/main/java/com/okta/tools/io/SubresourceIntegrityStrippingHack.java, src/main/java/com/okta/tools/io/SubresourceIntegrityStrippingURLConnection.java
Issue #272 states:
> When running withokta, the browser windows appears, but is just white. This started last night around 11pm ET. It is likely related to the 2019.02.19 release Okta did on Tuesday.
> 
> Running with OKTA_BROWSER_AUTH=false works.
> 
> 
>     1. Go to '...'
> 
>     2. Click on '....'
> 
>     3. Scroll down to '....'
> 
>     4. See error
> 
> 
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> Add any other context about the problem here.
The Okta login page is not rendered when OKTA_BROWSER_AUTH=true. This …
=> :bug: The browser just appears white

src/main/java/com/okta/tools/io/LoginPageInterceptingProtocolHandler.java
Issue #276 states:
> I just re-tested and it works for me without the warning messages.
> 
> I can get it to display a blank screen if I change the config so that the OKTA_ORG and OKTA_AWS_APP_URL are different domains - i.e. this does NOT work now (but it did up until last week):
> 
> OKTA_ORG=https://[corporate-okta-url-1]
> OKTA_AWS_APP_URL=https://[corporate-okta-url-2]/home/amazon_aws/[blah blah]
> 
> but if the org and aws url use the same domain it DOES work (up until the most recent 1.0.9 build this printed some errors to the command window) - i.e.
> 
> OKTA_ORG=https://[corporate-okta-url-1]
> OKTA_AWS_APP_URL=https://[corporate-okta-url-1]/home/amazon_aws/[blah blah]
> 
> _Originally posted by @mrbelowski in [#272 …
=> :bug: SRI hack doesn't work for multi-org

bin/Install-OktaAwsCli.ps1
Issue #281 states:
> The withokta alias is bound to the wrong Cmdlet (Get-OktaRoles) here:
> 
> [okta-aws-cli-assume-role/bin/Install-OktaAwsCli.ps1](https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/7e1ad72f96a0dbbf752bd11904135fb0a3eba3a2/bin/Install-OktaAwsCli.ps1#L105)
> 
> Line 105 in [7e1ad72](/oktadeveloper/okta-aws-cli-assume-role/commit/7e1ad72f96a0dbbf752bd11904135fb0a3eba3a2)
>  New-Alias -Name withokta -value Get-OktaRoles 
> 
> Run withokta default aws sts get-caller-identity
> 
> aws sts get-caller-identity is called after populating the default profile with credentials from Okta.
> 
> **Screenshots**
> N/A
> 
> Affects all releases …
=> :bug: withokta aliased to listroles on Windows

bin/install.sh
Seems like a copy pasta mistake in the install script creating two of the same functions. 
Solution
--------
Remove one of them!
=> Remove duplicate okta-aws function in install script

bin/install.sh
- It seems like the `bin/install.sh` script is supposed to be able to be used to upgrade an existing installation
since it will leave existing configuration files in place if they already exist; however, it fails to actually upgrade
because it does not update the `okta-aws-cli.jar` symlink to point to the new version of the JAR file since it is
not passing the `-f` flag to `ln`. This adds the `-f` flag to that `ln` call.
Solution
--------
=> Update jar symlink even if it already exists

src/main/java/com/okta/tools/authentication/BrowserAuthentication.java, src/main/java/com/okta/tools/helpers/RoleHelper.java, src/main/java/com/okta/tools/saml/AwsSamlRoleUtils.java
- The javafx window remains open and never shuts down once user authenticates (https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/317)
- Multiple roles are not handles correctly due to order of roleArn and principal being incorrect in map (this reverts previous change https://github.com/oktadeveloper/okta-aws-cli-assume-role/commit/ecbf26ecd2b0b460496cb9131ec8f5202cab421b#diff-13509f60aa8d183ec80dc2582dc38e74R49)
- I would like more flexibility for the OKTA_AWS_ROLE_TO_ASSUME env variable to be a full arn or just a name since in my scenario we are wrapping this tool and supporting multiple accounts and roles
Solution
--------
- check for relative path in form /saml
- fix order of role arn map
- modify code that selects role to check …
=> fix browser auth issue, multiple roles, and make role to assume more flexible

bin/install.sh
Quoted arguments are not preserved in BASH scripts.
Solution
--------
Preserving quoted arguments by wrapping `$@` with quotes (`"$@"`).
=> Preserving quotes in arguments for BASH scripts. (fixes #297)

src/main/java/com/okta/tools/OktaAwsConfig.java
- After setting up `OKTA_PASSWORD_CMD` to use `lpass show --password okta.com`, I noticed that if the LastPass CLI needed to reprompt for my LastPass master password, it was failing and the Okta AWS CLI was swallowing any error messages.
Solution
--------
- Inheriting the error stream means that the password command's error message will actually show up and inheriting the input stream allows the password command to prompt for anything it needs such as the LastPass CLI. This leaves standard output as a pipe since that is what is used to retrieve the password as usual.
=>  🐛 Inherit input and error streams for password command

src/main/java/com/okta/tools/WithOkta.java
- With #303, the call to `removeProfileArguments` moved out of only OKTA_ENV_MODE. I don't think this is correct since it was specifically added in #185 which added OKTA_ENV_MODE.
Solution
--------
- I have moved the call to `removeProfileArguments` back to only the OKTA_ENV_MODE execution path.
- I have also added support for removing `--profile=*` arguments as well since that is also a valid use of the `aws` CLI.
=>  🐛 Only remove --profile arg when in OKTA_ENV_MODE

Readme.MD, src/main/java/com/okta/tools/OktaAwsConfig.java
Need different settings for different AWS profiles.
Solution
--------
This is my attempt at providing a solution for #304. I've updated the docs in this pull request to explain what I've done.
=> Adding per profile override feature

src/main/java/com/okta/tools/authentication/OktaMFA.java, src/main/java/com/okta/tools/helpers/HttpHelper.java
A v2.0 code refactor (#280) / cleanup broke a few JSON traversals needed to support Okta MFA
Solution
--------
Reverts broken JSON traversal for the polling URL to prior implementation & short-circuits polling loop on success (at which point `FACTOR_RESULT` no longer exists)
Fixes #316
=> Fix Okta Push polling exception

src/main/java/com/okta/tools/authentication/BrowserAuthentication.java
When using web browser authentication if there is only one AWS role available to the user AWS returns a 302 and the javafx browser does not see the event. This results in the javafx browser sitting on the logged in AWS console page and never returning.
Solution
--------
Monitor the `locationProperty` for changes instead of the `stateProperty`.
Fixes https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/328
=> web browser auth single role fix

src/main/java/com/okta/tools/saml/AwsSamlRoleUtils.java, src/main/java/com/okta/tools/saml/SamlResponseUtils.java
See Issue #344.
Solution
--------
Use the "Destination" from the SAML response.
=> Issue #344 - Use destination from SAML response

bin/install.sh
You cannot logout from your AWS account using 'awscli logout' command.
Solution
--------
Fix the argument management on 'withokta' script
=> Fix 'awscli logout' command

Readme.MD, bin/install.sh
On a corporate managed EC2 instance I had a requirement to run the Okta AWS tools so that I could manipulate and interrogate the infrastructure. The EC2 is deployed into a VPC that mandates the use of a proxy to access the internet.
Java doesn't seem to have an environment-variable-based way of configuring a proxy at runtime.
Solution
--------
It seemed that the most appropriate way to make this work was to modify the wrapper script that calls the `com.okta.tools.WithOkta` class to append the `https.proxyHost` and `https.proxyPort` settings to the java command line.
The change creates a variable called `PROXY_CONFIG` if there is an environment variable named `http_proxy` set to a non-empty value, and it could be parsed by a `bash(1)` regular-expression. …
=> Modified the install.sh to make the withokta script slightly proxy-aware

src/main/java/com/okta/tools/WithOkta.java
When `OKTA_ENV_MODE=true` the `AWS_DEFAULT_REGION` is always set to us-east-1.  
Solution
--------
Pass `OKTA_AWS_REGION` to `AWS_DEFAULT_REGION`.
=> sending region to env mode

Readme.MD
Per https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/340, the latest version of this library requires java 11. 
Solution
--------
This updates the documentation to reflect this.
=> update doc for java 11 requirement

bin/install.sh
If you run the following snippet from your `install.sh`:
`curl --head --silent https://github.com/oktadeveloper/okta-aws-cli-assume-role/releases/latest`
You will notice the "Location" element you look for is now "location". I don't know why the case
changed but it makes the install script break. The output now looks like the following (some elements redacted):
```
date: Fri, 28 Feb 2020 15:49:14 GMT
content-type: text/html; charset=utf-8
server: GitHub.com
status: 302 Found
vary: X-PJAX, Accept-Encoding, Accept, X-Requested-With
location: https://github.com/oktadeveloper/okta-aws-cli-assume-role/releases/tag/v2.0.4
cache-control: no-cache
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 1; …
```
=> Adjust the install script to account for the changing GitHub output

bin/install.sh
GitHub has introduced a redirect to the `/releases/latest` path on all repositories.
Solution
--------
Follow the path, and only select the relevant url.
=> Fix retrieval of latest release tag url

Readme.MD, src/main/java/com/okta/tools/OktaAwsCliEnvironment.java, src/main/java/com/okta/tools/OktaAwsConfig.java, src/main/java/com/okta/tools/authentication/BrowserAuthentication.java, src/test/java/com/okta/tools/RoleHelperTest.java, src/test/java/com/okta/tools/authentication/OktaFactorSelectorTest.java, src/test/java/com/okta/tools/helpers/ProfileHelperTest.java, src/test/java/com/okta/tools/saml/OktaSamlTest.java
When using the Identity Provider (IdP) factor authentication ([Custom IdP Factor Authentication](https://help.okta.com/en/prod/Content/Topics/Security/MFA_Custom_Factor.htm)), there are additional SAML requests to the user authentication flow, which does not contain a relevant SAML assertion for parsing.
Solution
--------
Added an additional optional parameter ```OKTA_IGNORE_SAML_REQ_CONTAIN``` to allow users to skip specific URLs that contains a string.
=> Support okta idp factor

src/main/java/com/okta/tools/authentication/CookieManager.java
Use `CookieHandler.getDefault()` instead of the `com.sun.webkit.network.CookieManager` internal class.
`CookieHandler.getDefault()` returns an instance of `com.sun.webkit.network.CookieManager` so this change results in the same behavior.
This change fixes this error at runtime:
```
Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: class com.okta.tools.authentication.CookieManager (in unnamed module @0x1ce24091) cannot access class com.sun.webkit.network.CookieManager (in module javafx.web) because module javafx.web does not export com.sun.webkit.network to unnamed module @0x1ce24091
```
Solution
--------
=> Don't use internal class

Readme.MD, bin/Install-OktaAwsCli.ps1, bin/install.sh
Since the repository move from oktadeveloper to oktadev, the links are now pointing to the wrong place
Solution
--------
Change oktadeveloper to oktadev
=> changing oktadeveloper to oktadev

Readme.MD
The linked to docs in the README point towards setting up the AWS SSO integration, which does not work with this repo, as I discovered after wasting a handful of hours. This repo instead relies on the end-user having setup the AWS Federated integration, which is different, and does work with this tool.
Solution
--------
Improve the README, linking to the appropriate docs for this CLI to work, while also still linking to the original place, as it does offer an alternative approach in using the AWS CLI directly, which some people may prefer, but being clear that the two approaches are not equivalent and that this CLI will not work with both.
=> Improve documentation on configuring AWS / Okta

src/main/java/com/okta/tools/authentication/OktaMFA.java
The first response for sms authentication doesn't have the session_token
in the response. Handle this case by testing for the SESSION_TOKEN in
the response before reading it.
Co-Authored-By: agopi@thumbtack.com
Signed-off-by: Anuj Varma <anujvarma@thumbtack.com>
https://github.com/oktadev/okta-aws-cli-assume-role/issues/382
https://github.com/oktadev/okta-aws-cli-assume-role/issues/349
Solution
--------
Handle the case by testing for the SESSION_TOKEN in
the response before reading it in the case of sms token where the reponse for verify removed the session_token.
https://developer.okta.com/docs/reference/api/authn/#verify-sms-factor
=> Fix sms authentication, by checking verifyResponse

pom.xml
When possible 3rd party repositories should be avoided.
It doesn't look like this build actually needed that repo
=> Remove 3rd party Shiboleth repository from pom

pom.xml, src/main/java/com/okta/tools/authentication/BrowserAuthentication.java, src/main/java/com/okta/tools/authentication/CookieManager.java, src/main/java/com/okta/tools/helpers/CookieHelper.java
All cookies seen are stored in disk. Cookies name can clash between sites causing the OKTA cookies to be overwritten. 
Solution
--------
Filter cookies to be stored by host.
=> Fix cookie support
