- Readme.MD
Adding content for license and support. @joelfranusic-okta
> Readme update

- Readme.MD
- config.properties
- src/main/java/com/okta/tools/awscli.java
- src/main/java/com/okta/tools/config.properties
Current implementation requires user input. This pull request adds support for reading values from config.properties such that no input is required.
> Add parameters to support silent mode

- .gitignore
- pom.xml
I made some modifications to the POM for this project to improve the experience for users that want to build it using maven, and also to have the maven build generate a single JAR that contains all dependencies, rather than having to deal with copying multiple JAR dependencies around.
> Modified project POM so it defines all dependencies and build a single jar for execution.

- src/main/java/com/okta/tools/aws/settings/Configuration.java
- src/main/java/com/okta/tools/aws/settings/Settings.java
- src/main/java/com/okta/tools/awscli.java
- src/test/java/com/okta/tools/aws/settings/ConfigurationTest.java
When writing a profile to an empty configuration, that will also be the
default profile.
> Support empty Configuration

- src/main/java/com/okta/tools/OktaAwsCliAssumeRole.java
- src/main/java/com/okta/tools/awscli.java
Once login you could not logout easily ( you need to remove by hand the session file )
The session file end up in the working folder which can leads to security issue
If there is only one role available it does not auto select it
Solution
--------
Moving the session to HOME directory
Adding a 'logout' command
Autoselect role if only one detected
> Add logout command / Session storage in home / Auto select role

- src/main/java/com/okta/tools/OktaAwsCliAssumeRole.java
- src/main/java/com/okta/tools/WithOkta.java
- src/main/java/com/okta/tools/aws/settings/MultipleProfile.java
- src/main/java/com/okta/tools/aws/settings/Profile.java
- src/main/java/com/okta/tools/awscli.java
Multiple profiles can not be open at the same time without reauthenticating
Solution
--------
A profile ini file was made to store all of the profile information, so that it can be checked if they are active.
> BC-MultipleProfiles

- .travis.settings.xml
- .travis.yml
- pom.xml
> Add Travis config

- .vscode/settings.json
- Readme.MD
Readme was confusing.
Solution
--------
Restructure to be less confusing, especially:
* Avoid talking too much about specific platforms (thanks @AlainODea)
* Keep the getting started instructions simple and clear at the top
> :memo: Update readme

- src/main/java/com/okta/tools/authentication/OktaMFA.java
A menu of factors is shown even if there is only one factor. This is superfluous.
Solution
--------
Only show MFA menu if there are two or more eligible factors.
> :art: Hide MFA menu if only one eligible factor

- src/main/java/com/okta/tools/authentication/BrowserAuthentication.java
If statement uses inconsistent style.
Solution
--------
Put if statement into consistent style.
> :art: Fix if-statement parens style

- src/main/java/com/okta/tools/LogoutHandler.java
- src/main/java/com/okta/tools/WithOkta.java
- src/main/java/com/okta/tools/awscli.java
When using withokta exclusively (as we do), it is frustrating that there is no logout function.
Solution
--------
Allow logout from withokta as ./withokta logout. It has to be the first command-line parameter.
> :seedling: Logout from withokta

- Readme.MD
- bin/Install-OktaAwsCli.ps1
- bin/install.sh
- Not practically installable #88
- Update documentation on Okta Help Center #93
-  Readme is broken/confusing #136
Solution
--------
- Provide Windows installer (PowerShell)
- Provide macOS/Linux install (Bourne Shell)
- Update Readme to reflect new installers
- Update Readme to reflect supported OSes
- Update Readme to remove confusing/conflicting guidance
- Update Readme to remove history junk
> :bug: Fix #88 #93 #136

- pom.xml
com.okta.sdk dependencies are not used.
Solution
--------
Remove them as a followup to #150.
> :art: Remove unused com.okta.sdk dependencies

- bin/install.sh
Typo in install script causes error
Solution
--------
Added missing letter
> Fixing typo in install script

- src/main/java/com/okta/tools/authentication/BrowserAuthentication.java
- src/main/java/com/okta/tools/helpers/CookieHelper.java
Browser auth now runs every time. The cookies aren't saved.
Regression introduced by #145.
Solution
--------
- Set cookie domain during browser auth
> :bug: Cookie domain missing

- src/main/java/com/okta/tools/OktaAwsConfig.java
https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/124
The classpath used to be resolved if a configuration file was not present
Solution
--------
Add back this resolution
> Add classpath search if no configuration file is found (Fix #124)

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
It can be difficult to know how to describe a bug or a desired features effectively or consistently. This makes it harder to report issues or request features. It also makes it more difficult for contributors to efficiently address these gaps for users.
Solution
--------
Add some templates to give the contributors and users some assistance in structuring reports about issues we encounter or features we would like to see.
> :art: Update issue templates

- Readme.MD
Issue #188 states:
> **Is your feature request related to a problem? Please describe.**
> This is not really a feature request, but a notification that I have built a docker image that makes installing and using this tool easier (IMHO). I'm suggesting that it be added to the readme, but I would like a few more people to test it.
> 
> The docker image is here:
> https://hub.docker.com/r/tomsmithokta/okta-awscli-java/
> 
> The github repo (Dockerfile) is here:
> https://github.com/tom-smith-okta/okta-awscli-java
Solution
--------
- Describe process for Docker-based install
Resolves #188
> :memo: Docs for @tom-smith-okta's Docker install

- Readme.MD
- bin/Install-OktaAwsCli.ps1
- bin/install.sh
Clobbers aws and sls commands
Solution
--------
- Use okta-aws and okta-sls as alias names
@tom-smith-okta this is part of the follow-up to #203
> :bug: Clobbers aws and sls commands

- src/main/java/com/okta/tools/OktaAwsCliAssumeRole.java
OKTA_AWS_ROLE_TO_ASSUME doesn't work as documented.
Solution
--------
- Default to envvar or config instead of null
> :bug: OKTA_AWS_ROLE_TO_ASSUME doesn't work

- pom.xml
Issue #218 states:
> Attempting to use OKTA_BROWSER_AUTH=true on Java 11 fails with the following stacktrace:
> 
> ```
> Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
> 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
> 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:6 …
```
> :bug: OKTA_BROWSER_AUTH broken on Java 11

- src/main/java/com/okta/tools/authentication/OktaAuthentication.java
- src/main/java/com/okta/tools/authentication/OktaMFA.java
- src/main/java/com/okta/tools/helpers/HttpHelper.java
- src/main/java/com/okta/tools/saml/AwsSamlRoleUtils.java
- src/main/java/com/okta/tools/saml/OktaSaml.java
Issue #214 states:
> Tried this utility behind proxy, try to set the proxy different ways none of them seems to be working.
> 
> 1. Set the proxy outside of the utility -Djava.net.useSystemProxies=true, then it gives the below error
> 
> 2. Also tried to set the proxy at the Java Path.
> 
> ```
> java -Djava.net.useSystemProxies=true -Dhttps.proxyHost=_**.**.com -Dhttps.proxyPort=_*** -classpath okta-aws-cli-1.0.2.jar com.okta.tools.awscli
> Sep 30, 2018 8:42:13 PM org.apache.http.impl.execchain.RetryExec execute
> INFO: I/O exception (java.net.SocketException) caught when processing request to {tls}->[http://proxy.cna.com:8080->https](http://proxy.cna.com:8080-%3Ehttps)
> ://cnapreview.okta.com:443: Malformed reply from SOCKS server
> Sep 30, 2018 …
```
> :bug: Issues working behind Proxy

- Readme.MD
pasring -> parsing
addtional -> additional
Small typos in the Readme
Solution
--------
Replace with correct spelling.
> Fix some small typos.
